### ISSUE TITLE
Error :  too many values to unpack

### ISSUE THREAD

**Issue by ThomasPoty** [ahes/prometheus-barman-exporter#1]
Hi,
When I manually launch barman-exporter, I got this error : 

```/usr/local/bin/barman_exporter.py 
Traceback (most recent call last):
  File "/usr/local/bin/barman_exporter.py", line 41, in list_backup
    server_name_and_ts, date, size, wal_size = backup_line.split("-")
ValueError: too many values to unpack (expected 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/barman_exporter.py", line 154, in <module>
    core.REGISTRY.register(BarmanCollector(args.servers))
  File "/usr/lib/python3.4/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/lib/python3.4/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "/usr/local/bin/barman_exporter.py", line 122, in collect
    backups_done, backups_failed = barman.list_backup(server_name)
  File "/usr/local/bin/barman_exporter.py", line 48, in list_backup
    server_name_and_ts, status = backup_line.split("-")
ValueError: too many values to unpack (expected 2)
```

barman version is 2.8
Python version is Python 3.4.5

**Comment by ThomasPoty** [comment]
This bug is fixed by PR #2
