### ISSUE TITLE
barman-exporter service dont start

### ISSUE THREAD

**Issue by alexey1607** [ahes/prometheus-barman-exporter#8]
Hello,

the barman-exporter service has crashed and is not starting. We installed pgbouncer on the server and changed the default port for postgresql and reconfigured barman.

barman check backup and backups show OK, But the exporter does not start.

The error is this:

```
Traceback (most recent call last):
  File "/opt/prometheus/exporters/barman_exporter/barman_exporter", line 175, in <module>
    core.REGISTRY.register(BarmanCollector(args.servers))
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "/opt/prometheus/exporters/barman_exporter/barman_exporter", line 127, in collect
    backups_done, backups_failed = barman.list_backup(server_name)
  File "/opt/prometheus/exporters/barman_exporter/barman_exporter", line 43, in list_backup
    backup['wal_size'] = wal_size.split(":")[1].strip()
IndexError: list index out of range
```

**Comment by ahes** [comment]
barman-exporter no longer runs as a service. Please install node-exporter and run barman-exporter from cron to save textfile which will be digested by node-exporter. See README.md for that.

**Comment by ahes** [comment]
I uploaded the new code today. It again supports running as a service. .
