### ISSUE TITLE
barman cannot start | return version[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by enggarranu** [ahes/prometheus-barman-exporter#9]
hi Team,
I getting error when run #barman-exporter -f ./test.prom -u postgres

```
root@postgres:~# barman-exporter -f ./test.prom -u postgres
Traceback (most recent call last):
  File "/usr/local/bin/barman-exporter", line 9, in <module>
    load_entry_point('barman-exporter==1.0.7', 'console_scripts', 'barman-exporter')()
  File "/usr/local/lib/python3.5/dist-packages/barman_exporter/barman_exporter.py", line 220, in main
    write_metrics_to_file(args)
  File "/usr/local/lib/python3.5/dist-packages/barman_exporter/barman_exporter.py", line 258, in write_metrics_to_file
    registry = BarmanCollector(Barman(), args.servers)
  File "/usr/local/lib/python3.5/dist-packages/barman_exporter/barman_exporter.py", line 22, in __init__
    self.check_barman_version()
  File "/usr/local/lib/python3.5/dist-packages/barman_exporter/barman_exporter.py", line 25, in check_barman_version
    barman_version = tuple(int(v) for v in self.version().split('.'))
  File "/usr/local/lib/python3.5/dist-packages/barman_exporter/barman_exporter.py", line 37, in version
    return version[0]
IndexError: list index out of range
root@postgres:~# barman -v
2.3

```
please help me, how to fix the issue
Thanks in advance

**Comment by ArjonBu** [comment]
I am having the same issue
# sudo -u barman /var/lib/barman/.local/bin/barman-exporter -l 0.0.0.0:9780 -c 3600
IndexError: list index out of range

**Comment by ArjonBu** [comment]
@enggarranu Did you find a solution?

**Comment by valumar** [comment]
I fixed the issue the problem is related to barman version check.

**Comment by ArjonBu** [comment]
Will you merge and push to pip?

**Comment by ahes** [comment]
Uploaded to pip. Thanks for pull request.
